### ISSUE TITLE
Support for assumed roles

### ISSUE THREAD

**Issue by rootd00d** [cosmin/route53-transfer#25]
I seem to get an error when running this under an assumed role --

```
$ route53-transfer --access-key-id=$AWS_ACCESS_KEY_ID --secret-key=$AWS_SECRET_ACCESS_KEY dump tasktop.com -
Traceback (most recent call last):
  File "/usr/local/bin/route53-transfer", line 29, in <module>
    app.run(params)
  File "/usr/local/lib/python2.7/site-packages/route53_transfer/app.py", line 248, in run
    dump(con, zone_name, get_file(filename, 'w'), vpc=vpc)
  File "/usr/local/lib/python2.7/site-packages/route53_transfer/app.py", line 202, in dump
    zone = get_zone(con, zone_name, vpc)
  File "/usr/local/lib/python2.7/site-packages/route53_transfer/app.py", line 57, in get_zone
    res = con.get_all_hosted_zones()
  File "/usr/local/lib/python2.7/site-packages/boto/route53/connection.py", line 126, in get_all_hosted_zones
    body)
boto.route53.exception.DNSServerError: DNSServerError: 403 Forbidden
<?xml version="1.0"?>
<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>InvalidClientTokenId</Code><Message>The security token included in the request is invalid</Message></Error><RequestId>e23085b7-f27b-11e8-beff-6d5bf4106f1f</RequestId></ErrorResponse>
```

**Comment by adamjt** [comment]
@rootd00d I was able to use assumed roles with this change, then running the build and install tasks in setup.py

```
diff --git a/route53_transfer/app.py b/route53_transfer/app.py
index bfbaf54..8332413 100644
--- a/route53_transfer/app.py
+++ b/route53_transfer/app.py
@@ -49,7 +49,8 @@ def get_aws_credentials(params):
             secret_key = f.read().strip()
     else:
         secret_key = params.get('--secret-key') or environ.get('AWS_SECRET_ACCESS_KEY')
-    return access_key, secret_key
+    security_token = environ.get('AWS_SESSION_TOKEN')
+    return access_key, secret_key, security_token


 def get_zone(con, zone_name, vpc):
@@ -227,9 +228,10 @@ def up_to_s3(con, file, s3_bucket):


 def run(params):
-    access_key, secret_key = get_aws_credentials(params)
-    con = route53.connect_to_region('universal', aws_access_key_id=access_key, aws_secret_access_key=secret_key)
-    con_s3 = connect_s3(aws_access_key_id=access_key, aws_secret_access_key=secret_key)
+    access_key, secret_key, security_token = get_aws_credentials(params)
+    print(access_key, secret_key, security_token)
+    con = route53.connect_to_region('universal', aws_access_key_id=access_key, aws_secret_access_key=secret_key, security_token=security_token)
+    con_s3 = connect_s3(aws_access_key_id=access_key, aws_secret_access_key=secret_key, security_token=security_token)
     zone_name = params['<zone>']
     filename = params['<file>']
```
